module.exports = {
  hstem:      1,
  vstem:      3,
  vmoveto:    4,
  rlineto:    5,
  hlineto:    6,
  vlineto:    7,
  rrcurveto:  8,
  callsubr:   10,
  return:     11,
  endchar:    14,
  hstemhm:    18,
  hintmask:   19,
  cntrmask:   20,
  rmoveto:    21,
  hmoveto:    22,
  vstemhm:    23,
  rcurveline: 24,
  rlinecurve: 25,
  wcurveto:   26,
  hhcurveto:  27,
  callgsubr:  29,
  vhcurveto:  30,
  hvcurveto:  31
};
